packages:
    - "examples/**/*"
    - "packages/**/*"
    - "!**/.next/**"
    - "!**/dist/**"

catalog:
    viem: 2.23.4
    zod: 3.23.8
    zod-to-json-schema: 3.23.5
    "@solana/spl-token": 0.4.9
    "@solana/web3.js": 1.98.4
    ai: 4.0.3
    "@langchain/core": 0.3.6
    postchain-client: 2.0.2
    "@chromia/ft4": 2.0.2
    "@lit-protocol/lit-node-client": "7.0.2"
    "@lit-protocol/types": "7.0.2"
    "@lit-protocol/lit-auth-client": "7.0.2"
    "@lit-protocol/auth-helpers": "7.0.2"
    "@lit-protocol/constants": "7.0.2"
    "@lit-protocol/contracts-sdk": "7.0.2"
    "@lit-protocol/misc": "7.0.2"
    "@lit-protocol/wrapped-keys": "7.0.2"
    "@modelcontextprotocol/sdk": "1.0.4"
    "radix-web3.js": "0.3.1"
